# Generated by Django 3.1.6 on 2021-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('dfbp', models.FloatField()),
                ('dfsp', models.FloatField()),
                ('dfbtg', models.FloatField()),
                ('dfstg', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('unix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API', models.CharField(max_length=46)),
                ('TAPI', models.CharField(max_length=46)),
                ('interval', models.IntegerField()),
                ('check', models.IntegerField()),
                ('jalgas', models.IntegerField()),
                ('galymjan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('unix', models.IntegerField()),
            ],
        ),
    ]
