# Generated by Django 3.1.6 on 2021-07-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_config_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='bot',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='gmail',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
