# Generated by Django 3.1.6 on 2021-07-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210705_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('unix', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Result',
            new_name='Check',
        ),
        migrations.AddField(
            model_name='change',
            name='big',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
