# Generated by Django 3.1.6 on 2021-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210706_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='porog_check',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='porog_interval',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
