# Generated by Django 3.1.6 on 2021-07-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210707_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='json',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
